#!/bin/zsh

if [ ! -d test-server ]; then
  mkdir test-server
  cd test-server
  curl -sLO https://api.papermc.io/v2/projects/velocity/versions/3.1.2-SNAPSHOT/builds/184/downloads/velocity-3.1.2-SNAPSHOT-184.jar
  echo eula=true >> eula.txt
  mkdir plugins
  cd ..
fi

mvn clean package
rm test-server/plugins/velocity-discord-relay-*.jar 2&>/dev/null
cp target/velocity-discord-relay-*.jar test-server/plugins/
cd test-server
java -Xmx512M -Xms512M -jar velocity-*.jar nogui
